server:
  port: 7703
spring:
  application:
    name: apier-task
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/task?useSSL=false
    username: root
    password: 123456