server:
  port: 7703
spring:
  application:
    name: apier-task
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: local


---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/apier?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
logging:
  level:
    cn.apier.task: debug


---

spring:
  profiles: prod

  datasource:
    username: root
    password: 50M6Z3SNqJ*X
    url: jdbc:mysql://172.16.173.7:3306/apier?useSSL=false&useUnicode=true&characterEncoding=utf8

logging:
  level:
    cn.apier.task: debug
