server:
  port: 7703
spring:
  application:
    name: apier-task
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: local


---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/apier?useSSL=false
    username: root
    password: 123456

---

spring:
  profiles: prod

  datasource:
    username: root
    password: 50M6Z3SNqJ*X
    url: jdbc:mysql://172.16.173.7:3306/apier?useSSL=false

logging:
  level:
    cn.apier.task: debug
